### PR TITLE
Meal Plan 1

### PR DESCRIPTION
**Pull request by LizTW**
Let me know if this is the set up you're looking for.

### CODE REVIEW

**Comment by atherdon** [comment]
Yes, it works perfectly for us!

**Comment by atherdon** [comment]
Soon we'll plan how to create database schema via GraphQL for this data

**Comment by LizTW** [comment]
Ok then I'll add the rest in the same format - I'm thinking I'll do them as separate files (weekly plans) - does that work?

**Comment by atherdon** [comment]
yeah, separate files will be fine for now. and it's also hard to maintain
long data in one file and didn't make a mistake


On 19-Jul-2018 at 11:36 AM, Liz wrote:


Ok then I'll add the rest in the same format - I'm thinking I'll do them as
separate files (weekly plans) - does that work?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/types/pull/15#issuecomment-406246274>, or mute
the thread

**Pull request merged**
